"""Phase 7 — quality_pipeline.py: wires ensemble.py -> qe_rerank.py ->
llm_postedit.py -> roundtrip_verify.py into one function,
`produce_translation(source_text, direction) -> dict`, per the PRD.

This is where the PRD's "extraordinary quality" claim actually lives —
not in any single fine-tuned model, but in this decision chain:
1. Generate up to ~10 diverse candidates across all 3 engines (ensemble.py).
2. Pick the best one with reference-free QE (qe_rerank.py).
3. LLM-post-edit it, constrained to fluency-only changes (llm_postedit.py).
4. Round-trip verify the edit (roundtrip_verify.py). If it fails:
   a. Fall back to the pre-edit MT candidate if *its* round-trip passes
      (the LLM edit was the problem, not the underlying translation).
   b. Otherwise, flag the result low_confidence rather than silently
      shipping a drifted translation — never hide a failed check.

This machine cannot run torch (see logs/phase_6_status.md), so the actual
end-to-end pipeline is unverified here — but the fallback/decision logic
(the part that actually implements the PRD's quality guarantees) is fully
unit-tested with mocked stage functions, since that logic is what matters
most to get right and is entirely testable without real models.
"""
import ensemble
import llm_postedit
import qe_rerank
import roundtrip_verify


def produce_translation(source_text, direction, engines=None, roundtrip_engine="nllb",
                         similarity_threshold=roundtrip_verify.DEFAULT_SIMILARITY_THRESHOLD) -> dict:
    result = {
        "translation": None,
        "winning_engine": None,
        "winning_method": None,
        "qe_score": None,
        "qe_method": None,
        "roundtrip_similarity": None,
        "roundtrip_text": None,
        "low_confidence": False,
        "verification_note": None,
        "pre_edit_candidate": None,
        "post_edit_candidate": None,
        "edit_applied": False,
        "protected_spans": [],
        "all_candidates": [],
        "error": None,
    }

    # 1. Multi-candidate generation across the ensemble
    candidates = ensemble.generate_ensemble_candidates(source_text, direction, engines=engines)
    result["all_candidates"] = [(c.engine, c.method, c.text) for c in candidates]
    if not candidates:
        result["low_confidence"] = True
        result["error"] = "no candidates generated by any engine — see per-engine warnings in the log"
        return result

    # 2. QE-based reranking
    rerank_result = qe_rerank.rerank(source_text, candidates)
    winner = rerank_result["winner"]
    result["qe_method"] = rerank_result["method"]
    if winner is None:
        result["low_confidence"] = True
        result["error"] = "reranking produced no winner despite non-empty candidate list"
        return result
    result["winning_engine"] = winner.engine
    result["winning_method"] = winner.method
    for cand, score in rerank_result["scored"]:
        if cand is winner:
            result["qe_score"] = score
            break

    # 3. LLM post-editing, constrained to fluency-only changes
    postedit_result = llm_postedit.postedit(source_text, winner.text, direction)
    result["pre_edit_candidate"] = postedit_result["pre_edit"]
    result["post_edit_candidate"] = postedit_result["post_edit"]
    result["edit_applied"] = postedit_result["edit_applied"]
    result["protected_spans"] = postedit_result["protected_spans"]

    # 4. Round-trip verification, with the fallback chain
    verify_result = roundtrip_verify.verify(
        source_text, postedit_result["post_edit"], direction,
        threshold=similarity_threshold, engine_key=roundtrip_engine,
    )
    final_text = postedit_result["post_edit"]

    if not verify_result["passed"]:
        if postedit_result["edit_applied"] and postedit_result["pre_edit"] != postedit_result["post_edit"]:
            # the LLM edit may be what introduced the drift — check whether
            # the underlying MT candidate (before editing) round-trips fine
            pre_edit_verify = roundtrip_verify.verify(
                source_text, postedit_result["pre_edit"], direction,
                threshold=similarity_threshold, engine_key=roundtrip_engine,
            )
            if pre_edit_verify["passed"]:
                final_text = postedit_result["pre_edit"]
                verify_result = pre_edit_verify
                result["verification_note"] = (
                    "post-edited translation failed round-trip verification; fell back to the "
                    "pre-edit MT candidate, which passed"
                )
            else:
                result["low_confidence"] = True
                result["verification_note"] = (
                    "both the post-edited and pre-edit candidates failed round-trip verification "
                    "— shipped the post-edit anyway, flagged low_confidence rather than blocking output"
                )
        else:
            result["low_confidence"] = True
            result["verification_note"] = (
                "failed round-trip verification (no LLM edit was applied to fall back from) "
                "— flagged low_confidence rather than blocking output"
            )

    result["translation"] = final_text
    result["roundtrip_similarity"] = verify_result["similarity"]
    result["roundtrip_text"] = verify_result["roundtrip_text"]
    return result


if __name__ == "__main__":
    import sys
    text = sys.argv[1] if len(sys.argv) > 1 else "আমি ভালো আছি #blessed"
    direction = sys.argv[2] if len(sys.argv) > 2 else "bn2en"
    result = produce_translation(text, direction)
    for k, v in result.items():
        print(f"{k}: {v}")
